### ISSUE TITLE
changing state of torrents doesnt remove (or add them) to active selected status tab

### ISSUE THREAD

**Issue by rezad1393** [equeim/tremotesf2#117]
this is a regression (didnt happen before)
if I select the paused state tab, and then start a torrent, it wont be removed from active UI area (that supposed to only show paused torrent) and I have to switch tabs to see it.

this also happens with all other state tabs too like seeding tab
for example if I have downloading torrent state tab selected and see what torrent are downloading, if a torrent gets new peers and starts to download then it doesnt automatically get added to the active UI area ,which mean I dont see it as downloading. so I have to switch to another state tab and then switch back to downloading tab to see it.

the numbers shown for each state is updated correctly. so I can see that for example the torrent I have started have been removed from paused state (pause torrent total decreases by one) and downloading torrent total increases by one.

**Comment by rezad1393** [comment]
also selecting and deselecting files from inside the torrent so that size of torrent changes also doesnt move torrent if sorted by size to download. so I have to click twice on size column to sort again.
this points me to UI area not getting updated.

**Comment by rezad1393** [comment]
also selecting and deselecting files from inside the torrent so that size of torrent changes also doesnt move torrent if sorted by size to download. so I have to click twice on size column to sort again.
this points me to UI area not getting updated.

if I recall correctly this didnt happen before too.

**Comment by equeim** [comment]
Fixed in 1.11.3

**Comment by rezad1393** [comment]
I have installed from flatpak and the version says 1.11.3 and it still happens,.
you meant 1.11.4?

**Comment by equeim** [comment]
I just checked version from Flathub and it doesn't reproduce for me. Since Tremotesf requests information from transmission-daemon with several seconds interval (5 s by default), there is often a delay before torrents list is updated. Information on sidebar should be now updated simultaneously with torrents list, though.

**Comment by rezad1393** [comment]
I have tested again I and I see them again.
my torrents usually have low seeds so they don't start immediately  . so I can test it this way: start a torrent in stopped tab.
switch to downloading tab and wait. the torrent starts after a while but and I see in the left sidebar that the number of downloading torrent has increases but the downloading tab that I am in doesn't show that. if I switch to another tab and then back to downloads it is there then.
